language: go

go:
  - "1.x"
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - go get -t -v ./...
  - go get -v golang.org/x/time/rate
  - go vet ./...
script:
  # run all our tests with race detector
  - go test -v -race ./...
